name: open_dual_view
description: "A Flutter package to open applications in dual view mode on Android devices."
version: 1.0.0
repository: https://github.com/TheValkDokk/open_dual_view

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.valkdokk.open_dual_view
        pluginClass: OpenDualViewPlugin
